'use client'

import { useState } from 'react'
import ProtectedRoute from '@/components/auth/ProtectedRoute'
import DashboardLayout from '@/components/layout/DashboardLayout'
import OnboardingForm from '@/components/onboarding/OnboardingForm'
import BrandPreview from '@/components/onboarding/BrandPreview'
import AIOutputModal from '@/components/onboarding/AIOutputModal'
import { createBrandKit, GeneratedBrandKit, BrandKitData } from '@/lib/ai/brand'
import { supabase } from '@/lib/supabase'

export default function OnboardingPage() {
  const [generatedBrandKit, setGeneratedBrandKit] = useState<GeneratedBrandKit | null>(null)
  const [showModal, setShowModal] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleGenerate = async (formData: BrandKitData) => {
    setLoading(true)
    try {
      const brandKit = await createBrandKit(formData)
      setGeneratedBrandKit(brandKit)
      setShowModal(true)
    } catch (error) {
      console.error('Error generating brand kit:', error)
      // Handle error (show toast, etc.)
    } finally {
      setLoading(false)
    }
  }

  const handleSave = async (brandKit: GeneratedBrandKit) => {
    try {
      // Get current user
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('User not authenticated')

      // Get company
      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('user_id', user.id)
        .eq('name', brandKit.companyName)
        .single()

      if (!company) throw new Error('Company not found')

      // Update brand kit in database
      const { error } = await supabase
        .from('brand_kits')
        .update({
          tagline: brandKit.taglines[0] || '',
          voice: brandKit.brandVoice,
          colors: JSON.stringify(brandKit.colorPalette),
          style: brandKit.brandGuidelines,
          updated_at: new Date().toISOString()
        })
        .eq('company_id', company.id)

      if (error) throw error

      // Show success message
      console.log('Brand kit saved successfully!')
    } catch (error) {
      console.error('Error saving brand kit:', error)
      throw error
    }
  }

  const handleDownload = async (brandKit: GeneratedBrandKit) => {
    try {
      // Create a comprehensive brand kit document
      const brandKitDoc = `
# ${brandKit.companyName} Brand Kit

## Taglines
${brandKit.taglines.map((tagline, index) => `${index + 1}. ${tagline}`).join('\n')}

## Brand Voice
${brandKit.brandVoice}

## Color Palette
- Primary: ${brandKit.colorPalette.primary}
- Secondary: ${brandKit.colorPalette.secondary}
- Accent: ${brandKit.colorPalette.accent}
- Neutral: ${brandKit.colorPalette.neutral}
- Background: ${brandKit.colorPalette.background}

## Typography
- Primary Font: ${brandKit.typography.primary}
- Secondary Font: ${brandKit.typography.secondary}
- Body Font: ${brandKit.typography.body}

## Brand Guidelines
${brandKit.brandGuidelines}

---
Generated by Rock Foundation on ${new Date(brandKit.generatedAt).toLocaleDateString()}
      `.trim()

      // Create and download file
      const blob = new Blob([brandKitDoc], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${brandKit.companyName}-brand-kit.md`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Error downloading brand kit:', error)
      throw error
    }
  }

  const handleShare = async (brandKit: GeneratedBrandKit) => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: `${brandKit.companyName} Brand Kit`,
          text: `Check out the brand kit for ${brandKit.companyName}`,
          url: window.location.href
        })
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(window.location.href)
        console.log('Link copied to clipboard!')
      }
    } catch (error) {
      console.error('Error sharing brand kit:', error)
      throw error
    }
  }

  return (
    <ProtectedRoute>
      <DashboardLayout>
        <main className="flex flex-col gap-6 py-12">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Welcome to Rock Foundation
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
              Let's create your professional brand identity in just 4 simple steps. 
              Our AI will generate a complete brand kit tailored to your startup.
            </p>
          </div>
          
          <OnboardingForm onGenerate={handleGenerate} />
          <BrandPreview 
            brandKit={generatedBrandKit}
            onSave={handleSave}
            onDownload={handleDownload}
          />

          {/* AI Output Modal */}
          <AIOutputModal
            isOpen={showModal}
            onClose={() => setShowModal(false)}
            brandKit={generatedBrandKit}
            onSave={handleSave}
            onDownload={handleDownload}
            onShare={handleShare}
          />
        </main>
      </DashboardLayout>
    </ProtectedRoute>
  )
}
