'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { 
  Plus, 
  Download, 
  Edit, 
  Trash2, 
  Eye,
  Calendar,
  Building2,
  Palette,
  Type,
  FileText,
  Loader2,
  RefreshCw
} from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { GeneratedBrandKit } from '@/lib/ai/brand'
import { useRouter } from 'next/navigation'

interface SavedBrandKit {
  id: string
  company_id: string
  tagline: string
  tone: string
  logo_url: string
  colors: string
  voice: string
  style: string
  created_at: string
  updated_at: string
  company: {
    name: string
    industry: string
  }
}

export default function BrandKitDashboard() {
  const [brandKits, setBrandKits] = useState<SavedBrandKit[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedKit, setSelectedKit] = useState<SavedBrandKit | null>(null)
  const [showPreview, setShowPreview] = useState(false)
  const router = useRouter()

  useEffect(() => {
    loadBrandKits()
  }, [])

  const loadBrandKits = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      const { data, error } = await supabase
        .from('brand_kits')
        .select(`
          *,
          company:companies(name, industry)
        `)
        .eq('company.user_id', user.id)
        .order('created_at', { ascending: false })

      if (error) throw error
      setBrandKits(data || [])
    } catch (error) {
      console.error('Error loading brand kits:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleCreateNew = () => {
    router.push('/onboarding')
  }

  const handlePreview = (kit: SavedBrandKit) => {
    setSelectedKit(kit)
    setShowPreview(true)
  }

  const handleDownload = async (kit: SavedBrandKit) => {
    try {
      const colors = JSON.parse(kit.colors || '{}')
      
      const brandKitDoc = `
# ${kit.company.name} Brand Kit

## Tagline
${kit.tagline}

## Brand Voice
${kit.voice}

## Color Palette
- Primary: ${colors.primary || '#3B82F6'}
- Secondary: ${colors.secondary || '#8B5CF6'}
- Accent: ${colors.accent || '#10B981'}
- Neutral: ${colors.neutral || '#6B7280'}
- Background: ${colors.background || '#F9FAFB'}

## Brand Guidelines
${kit.style}

---
Generated by Rock Foundation on ${new Date(kit.created_at).toLocaleDateString()}
      `.trim()

      const blob = new Blob([brandKitDoc], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${kit.company.name}-brand-kit.md`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Error downloading brand kit:', error)
    }
  }

  const handleDelete = async (kitId: string) => {
    if (!confirm('Are you sure you want to delete this brand kit?')) return

    try {
      const { error } = await supabase
        .from('brand_kits')
        .delete()
        .eq('id', kitId)

      if (error) throw error
      
      setBrandKits(prev => prev.filter(kit => kit.id !== kitId))
    } catch (error) {
      console.error('Error deleting brand kit:', error)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header Actions */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
            Your Brand Kits
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            {brandKits.length} brand kit{brandKits.length !== 1 ? 's' : ''} created
          </p>
        </div>
        <Button
          onClick={handleCreateNew}
          className="bg-blue-600 hover:bg-blue-700 text-white"
        >
          <Plus className="w-4 h-4 mr-2" />
          Create New Brand Kit
        </Button>
      </div>

      {/* Brand Kits Grid */}
      {brandKits.length === 0 ? (
        <div className="text-center py-12">
          <div className="w-20 h-20 bg-gray-100 dark:bg-gray-700 rounded-full flex items-center justify-center mx-auto mb-4">
            <Palette className="w-10 h-10 text-gray-400" />
          </div>
          <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
            No brand kits yet
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-6">
            Create your first brand kit to get started with professional branding
          </p>
          <Button
            onClick={handleCreateNew}
            className="bg-blue-600 hover:bg-blue-700 text-white"
          >
            <Plus className="w-4 h-4 mr-2" />
            Create Your First Brand Kit
          </Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {brandKits.map((kit) => {
            const colors = JSON.parse(kit.colors || '{}')
            return (
              <div
                key={kit.id}
                className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden"
              >
                {/* Header */}
                <div className="p-6 border-b border-gray-200 dark:border-gray-700">
                  <div className="flex items-start justify-between">
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                        {kit.company.name}
                      </h3>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        {kit.company.industry}
                      </p>
                    </div>
                    <div className="flex items-center space-x-1">
                      <Button
                        onClick={() => handlePreview(kit)}
                        variant="ghost"
                        size="sm"
                      >
                        <Eye className="w-4 h-4" />
                      </Button>
                      <Button
                        onClick={() => handleDelete(kit.id)}
                        variant="ghost"
                        size="sm"
                        className="text-red-600 hover:text-red-700"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>

                {/* Content */}
                <div className="p-6 space-y-4">
                  {/* Tagline */}
                  <div>
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Tagline
                    </h4>
                    <p className="text-gray-900 dark:text-white font-medium">
                      {kit.tagline}
                    </p>
                  </div>

                  {/* Color Palette */}
                  <div>
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Color Palette
                    </h4>
                    <div className="flex space-x-2">
                      {Object.values(colors).slice(0, 4).map((color: string, index) => (
                        <div
                          key={index}
                          className="w-6 h-6 rounded border border-gray-300 dark:border-gray-600"
                          style={{ backgroundColor: color }}
                          title={color}
                        />
                      ))}
                    </div>
                  </div>

                  {/* Created Date */}
                  <div className="flex items-center text-sm text-gray-500 dark:text-gray-400">
                    <Calendar className="w-4 h-4 mr-1" />
                    Created {new Date(kit.created_at).toLocaleDateString()}
                  </div>
                </div>

                {/* Actions */}
                <div className="p-6 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-700/50">
                  <div className="flex space-x-2">
                    <Button
                      onClick={() => handlePreview(kit)}
                      variant="outline"
                      size="sm"
                      className="flex-1"
                    >
                      <Eye className="w-4 h-4 mr-1" />
                      Preview
                    </Button>
                    <Button
                      onClick={() => handleDownload(kit)}
                      variant="outline"
                      size="sm"
                      className="flex-1"
                    >
                      <Download className="w-4 h-4 mr-1" />
                      Download
                    </Button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* Preview Modal */}
      {showPreview && selectedKit && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-hidden">
            <div className="p-6 border-b border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
                    {selectedKit.company.name} Brand Kit
                  </h2>
                  <p className="text-gray-600 dark:text-gray-400">
                    {selectedKit.company.industry} • Created {new Date(selectedKit.created_at).toLocaleDateString()}
                  </p>
                </div>
                <Button
                  onClick={() => setShowPreview(false)}
                  variant="ghost"
                  size="sm"
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <div className="p-6 overflow-y-auto max-h-[60vh] space-y-6">
              {/* Tagline */}
              <div>
                <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
                  Tagline
                </h3>
                <p className="text-xl font-semibold text-blue-600 dark:text-blue-400">
                  {selectedKit.tagline}
                </p>
              </div>

              {/* Brand Voice */}
              <div>
                <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
                  Brand Voice
                </h3>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <p className="text-gray-700 dark:text-gray-300">
                    {selectedKit.voice}
                  </p>
                </div>
              </div>

              {/* Color Palette */}
              <div>
                <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">
                  Color Palette
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  {Object.entries(JSON.parse(selectedKit.colors || '{}')).map(([name, color]) => (
                    <div key={name} className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                      <div
                        className="w-full h-12 rounded-lg mb-2 border border-gray-300 dark:border-gray-600"
                        style={{ backgroundColor: color as string }}
                      />
                      <h4 className="font-medium text-gray-900 dark:text-white capitalize text-sm">
                        {name}
                      </h4>
                      <p className="text-xs text-gray-600 dark:text-gray-400 font-mono">
                        {color}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Brand Guidelines */}
              <div>
                <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
                  Brand Guidelines
                </h3>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <div className="prose dark:prose-invert max-w-none">
                    <div className="whitespace-pre-wrap text-gray-700 dark:text-gray-300 text-sm">
                      {selectedKit.style}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="p-6 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-700/50">
              <div className="flex space-x-3">
                <Button
                  onClick={() => handleDownload(selectedKit)}
                  className="bg-blue-600 hover:bg-blue-700 text-white flex-1"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download Kit
                </Button>
                <Button
                  onClick={() => setShowPreview(false)}
                  variant="outline"
                  className="flex-1"
                >
                  Close
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
